### ISSUE TITLE
Update for missing regions.

### ISSUE THREAD

**Issue by DaveyRance** [poshsecurity/AzurePublicIPAddresses#4]
In the version that can be downloaded as of PublicIPs_20190319.xml the following regions need to be updated.

brazilne
brazilse
southafrican
southafricaw

**Comment by kjacobsen** [comment]
Thanks, I try to stay on top of the new regions but these ones caught me by surprise. Fix will be up shortly.

**Comment by kjacobsen** [comment]
Hi,

sorry for the delay.

all missing regions have now been added.
